### ISSUE TITLE
start quiz in a new window

### ISSUE THREAD

**Issue by trash369** [wingkwong/react-quiz-component#152]
i am getting my quizes as json object stored in mongodb  then display as a list. 
![quizes](https://github.com/wingkwong/react-quiz-component/assets/24405777/89b45f04-4341-46c0-a5d3-6e241feba7c5)

is there anyway to start quiz in a new page after click start quiz button. i mean pass my JSON object to another page. I am using Nextjs

**Comment by wingkwong** [comment]
I think you've already answered your question. In your listing page (assuming it is `quiz/index.tsx`), you don't need to use `react-quiz-component`. Since you got your quiz data on your mongodb, you can still display the same as your screenshot. Then your custom button should redirect to a quiz page (assuming it is `quiz/[id].tsx`), in this page you can fetch the corresponding quiz object based on `id`, then pass to  `<Quiz />` with `disableSynopsis`.

**Comment by trash369** [comment]
Thank you @wingkwong  Now its working perfectly
